name: infracode-terraform
on:
  workflow_dispatch:
permissions: read-all
jobs:
  terraform:
    name: terrafom init plan apply
    runs-on: [rajnish-runner]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./
        
      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./
        
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./
